# Generated by Django 3.1.14 on 2023-09-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя покемона')),
                ('picture', models.ImageField(upload_to='', verbose_name='Изображение покемона')),
            ],
        ),
    ]
