# Generated by Django 3.1.14 on 2023-09-13 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Pokemons',
        ),
    ]
