# Generated by Django 3.1.12 on 2023-09-13 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0002_auto_20230913_2123'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pokemons',
            new_name='Pokemon',
        ),
    ]
