# Generated by Django 3.1.12 on 2023-09-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0008_auto_20230917_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='prev_evolution',
            new_name='previous_evolution',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Имя покемона'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='picture',
            field=models.ImageField(upload_to='', verbose_name='Изображение покемона'),
        ),
    ]
